version: '3'
services:
  db:
    image: postgres:12
    ports:
      - 5432:5432
    networks:
      - default
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=postgres
  backend:
    build: .
    tty: true
    ports:
      - 8000:8000
    volumes:
      - ./travelist/:/src/travelist/
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DEBUG=TRUE
      - DB_TYPE=postgres
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_DB=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - POSTGRES_HOST_AUTH_METHOD=trust
      - LOGGING_ROOT_LEVEL=DEBUG
    networks:
      - default
    depends_on:
      - db
